version: '3.8'

services:
  mkdocs:
    build: .
    container_name: isp-mkdocs
    ports:
      - "8001:8000"
    volumes:
      - .:/docs
    command: mkdocs serve --dev-addr=0.0.0.0:8000
    restart: unless-stopped
